version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  couchdb:
    image: couchdb
    #restart: always
    ports:
      - '5984:5984'
    environment:
      - COUCHDB_USER=devadm
      - COUCHDB_PASSWORD=qq    
    volumes:
      - /home/psh/psh_dev/github-io/github-io/tz-000029-rabbitmq/py-rabbit/learnamqp/tz-000001-init/learnamqp/db
  sender-web:
    build:
      context: ./
      dockerfile: docker-sender-web 
    ports:
      - "8080:8080"
      - "5678:5678" 
    links:
      - "rabbitmq"
      - "couchdb"
    depends_on:
      rabbitmq:
        condition: service_healthy
      couchdb:
        condition: service_started
    environment:
      FLASK_APP: "sender_web.webapp"
      FLASK_ENV: "development"
      FLASK_DEBUG: "0"
      LOGLEVEL: "DEBUG"
      APP_MODULE: "sender_web.webapp"
      GUNICORN_CMD_ARGS: "--workers=1 --worker-connections=2000  --bind=0.0.0.0:8080 --timeout=600 --threads=50"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"      
  receiver-web:
    build:
      context: ./
      dockerfile: docker-receive-web 
    links:
      - "rabbitmq"
      - "couchdb"
    depends_on:
      rabbitmq:
        condition: service_healthy
      couchdb:
        condition: service_started
    environment:
      LOGLEVEL: "DEBUG"
      APP_FILE: "receiver_weber.py"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"      
  writer-web:
    build:
      context: ./
      dockerfile: docker-writer-web 
    links:
      - "rabbitmq"
      - "couchdb"
    depends_on:
      rabbitmq:
        condition: service_healthy
      couchdb:
        condition: service_started
    environment:
      LOGLEVEL: "DEBUG"
      APP_FILE: "writer_weber.py"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"   
      COUCHDB_AUTH_TYPE: "COUCHDB_SESSION"
      COUCHDB_URL: "http://couchdb:5984"
      COUCHDB_USERNAME: "devadm"
      COUCHDB_PASSWORD: "qq"      